services:
  expo:
    build: .
    container_name: expo_app
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_NO_TELEMETRY=1
      - NODE_ENV=development
      - EXPO_DEVTOOLS=1
    volumes:
      - .:/app
      - /app/node_modules
    restart: always 
    command: ["npx", "expo", "start", "--dev-client", "--tunnel"]